# Generated by Django 5.2.17 on 2026-09-03 22:36

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], db_index=True, max_length=16, verbose_name='type')),
                ('url', models.URLField(max_length=1000, verbose_name='url')),
                ('mime_type', models.CharField(max_length=127, verbose_name='mime type')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('size_bytes', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='size in bytes')),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, help_text='Time-based media only (audio, video).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration in seconds')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', '-created_at'], name='media_type_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('type__in', ['audio', 'video']), _connector='OR'), name='media_duration_only_for_timed_types')],
            },
        ),
    ]
