# Generated by Django 5.2.17 on 2026-09-03 22:36

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fln_level', models.PositiveSmallIntegerField(help_text='The developmental level this question probes, 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='FLN level')),
                ('content', models.TextField(verbose_name='content')),
                ('layout', models.CharField(blank=True, choices=[('media_grid_choice', 'Media grid'), ('media_list_choice', 'Media list'), ('comparison_panel_choice', 'Comparison panel'), ('speech_response_prompt', 'Speech response'), ('passage_comprehension_choice', 'Passage comprehension')], max_length=32, verbose_name='layout')),
                ('type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('text', 'Text'), ('audio', 'Audio'), ('number', 'Number'), ('true_false', 'True / false'), ('file_upload', 'File upload')], max_length=32, verbose_name='type')),
                ('audio_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_described', to='media_assets.mediaasset', verbose_name='audio description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_illustrated', to='media_assets.mediaasset', verbose_name='image')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('file_upload', 'File upload')], max_length=16, verbose_name='type')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='curriculum.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'question answer',
                'verbose_name_plural': 'question answers',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('domain', models.CharField(choices=[('literacy', 'Literacy'), ('numeracy', 'Numeracy')], max_length=16, verbose_name='domain')),
            ],
            options={
                'verbose_name': 'question bank',
                'verbose_name_plural': 'question banks',
                'ordering': ['domain', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), models.F('domain'), name='question_bank_name_domain_ci_unique')],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='curriculum.questionbank', verbose_name='question bank'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('domain', models.CharField(choices=[('literacy', 'Literacy'), ('numeracy', 'Numeracy')], max_length=16, verbose_name='domain')),
                ('min_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='minimum level')),
                ('max_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='maximum level')),
                ('is_core', models.BooleanField(default=True, help_text='Only core skills gate placement; the rest are enrichment.', verbose_name='is core')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['domain', 'display_order', 'name'],
                'indexes': [models.Index(fields=['domain', 'is_core'], name='skill_domain_core_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_level__lte', models.F('max_level'))), name='skill_level_range_ordered'), models.CheckConstraint(condition=models.Q(('max_level__lte', 5), ('min_level__gte', 1)), name='skill_level_range_in_bounds')],
            },
        ),
        migrations.CreateModel(
            name='Subskill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('min_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='minimum level')),
                ('max_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='maximum level')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subskills', to='curriculum.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'subskill',
                'verbose_name_plural': 'subskills',
                'ordering': ['skill', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.subskill', verbose_name='subskill'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('true_false', 'True / false')], max_length=16, verbose_name='option type')),
                ('content', models.TextField(verbose_name='content')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='curriculum.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['question', 'is_correct'], name='option_question_correct_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=16, verbose_name='type')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='display order')),
                ('text_content', models.TextField(blank=True, verbose_name='text content')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_contents', to='media_assets.mediaasset', verbose_name='media')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='curriculum.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'question content',
                'verbose_name_plural': 'question contents',
                'ordering': ['question', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('question', 'display_order'), name='question_content_order_unique'), models.CheckConstraint(condition=models.Q(models.Q(('text_content', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='question_content_requires_text_or_media')],
            },
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['skill', 'display_order'], name='subskill_skill_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='subskill',
            constraint=models.CheckConstraint(condition=models.Q(('min_level__isnull', True), ('max_level__isnull', True), ('min_level__lte', models.F('max_level')), _connector='OR'), name='subskill_level_range_ordered'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subskill', 'fln_level'], name='question_subskill_level_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank', 'fln_level'], name='question_bank_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('fln_level__gte', 1), ('fln_level__lte', 5)), name='question_fln_level_in_range'),
        ),
    ]
