# Generated by Django 5.2.17 on 2026-08-26 08:36

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='content')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Difficulty from 1 (easiest) to 5 (hardest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='level')),
                ('type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('text', 'Text'), ('audio', 'Audio'), ('number', 'Number'), ('true_false', 'True / false'), ('file_upload', 'File upload')], max_length=32, verbose_name='type')),
                ('audio_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_described', to='media_assets.mediaasset', verbose_name='audio description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_illustrated', to='media_assets.mediaasset', verbose_name='image')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('file_upload', 'File upload')], max_length=16, verbose_name='type')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='curriculum.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'question answer',
                'verbose_name_plural': 'question answers',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='schools.schoolclass', verbose_name='class')),
            ],
            options={
                'verbose_name': 'question bank',
                'verbose_name_plural': 'question banks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='curriculum.questionbank', verbose_name='question bank'),
        ),
        migrations.CreateModel(
            name='QuestionLayout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'question layout',
                'verbose_name_plural': 'question layouts',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='question_layout_name_ci_unique')],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='curriculum.questionlayout', verbose_name='layout'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='subject_name_ci_unique')],
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='curriculum.subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.subject', verbose_name='subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='topic_name_ci_unique')],
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='curriculum.topic', verbose_name='topic'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('true_false', 'True / false')], max_length=16, verbose_name='option type')),
                ('content', models.TextField(verbose_name='content')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='curriculum.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['question', 'is_correct'], name='option_question_correct_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=16, verbose_name='type')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='display order')),
                ('text_content', models.TextField(blank=True, verbose_name='text content')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_contents', to='media_assets.mediaasset', verbose_name='media')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='curriculum.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'question content',
                'verbose_name_plural': 'question contents',
                'ordering': ['question', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('question', 'display_order'), name='question_content_order_unique'), models.CheckConstraint(condition=models.Q(models.Q(('text_content', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='question_content_requires_text_or_media')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank', 'level'], name='question_bank_level_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'type'], name='question_subject_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 5)), name='question_level_in_range'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['school_class', 'subject', 'topic'], name='qbank_class_subj_topic_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('name', 'school_class', 'subject', 'topic'), name='question_bank_identity_unique'),
        ),
    ]
