# Generated by Django 5.2.17 on 2026-09-04 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalLessonPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('literacy', 'Literacy'), ('numeracy', 'Numeracy')], max_length=16, verbose_name='domain')),
                ('from_level', models.PositiveSmallIntegerField(verbose_name='from level')),
                ('to_level', models.PositiveSmallIntegerField(verbose_name='to level')),
                ('resource_tier', models.CharField(choices=[('minimal', 'Chalkboard and voice only'), ('basic', 'Paper, printed materials'), ('equipped', 'Manipulatives, some devices')], max_length=16, verbose_name='resource tier')),
                ('content', models.JSONField(default=dict, verbose_name='content')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('focus_subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_plans', to='curriculum.subskill', verbose_name='focus subskill')),
            ],
            options={
                'verbose_name': 'canonical lesson plan',
                'verbose_name_plural': 'canonical lesson plans',
                'ordering': ['domain', 'from_level', 'focus_subskill'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('domain', models.CharField(blank=True, choices=[('literacy', 'Literacy'), ('numeracy', 'Numeracy')], max_length=16, verbose_name='domain')),
                ('origin', models.CharField(choices=[('manual', 'Created by a teacher'), ('auto', 'Formed by the system')], default='manual', max_length=16, verbose_name='origin')),
                ('is_primary', models.BooleanField(default=False, help_text='The group whose plan the teacher actually runs. A child matches several; without this the teacher opens Monday to competing plans.', verbose_name='is primary')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16, verbose_name='status')),
                ('resource_tier', models.CharField(choices=[('minimal', 'Chalkboard and voice only'), ('basic', 'Paper, printed materials'), ('equipped', 'Manipulatives, some devices')], default='basic', max_length=16, verbose_name='resource tier')),
                ('stable_until', models.DateTimeField(blank=True, null=True, verbose_name='stable until')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.school', verbose_name='school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupCriterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('level', 'FLN level'), ('skill', 'Weak in a skill'), ('subskill', 'Weak in a subskill'), ('class', 'In a class')], max_length=16, verbose_name='type')),
                ('comparator', models.CharField(blank=True, choices=[('eq', 'Equals'), ('gte', 'At or above'), ('lte', 'At or below')], max_length=8, verbose_name='comparator')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='level')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='instruction.group', verbose_name='group')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_criteria', to='schools.schoolclass', verbose_name='class')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_criteria', to='curriculum.skill', verbose_name='skill')),
                ('subskill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_criteria', to='curriculum.subskill', verbose_name='subskill')),
            ],
            options={
                'verbose_name': 'group criterion',
                'verbose_name_plural': 'group criteria',
                'ordering': ['group', 'type'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(verbose_name='joined at')),
                ('left_at', models.DateTimeField(blank=True, help_text='Null while a current member.', null=True, verbose_name='left at')),
                ('join_reason', models.CharField(blank=True, choices=[('matched', 'Matched the criteria'), ('added', 'Added by a teacher'), ('progressed', 'Progressed past the criteria'), ('removed', 'Removed by a teacher'), ('archived', 'Group archived')], max_length=16, verbose_name='join reason')),
                ('leave_reason', models.CharField(blank=True, choices=[('matched', 'Matched the criteria'), ('added', 'Added by a teacher'), ('progressed', 'Progressed past the criteria'), ('removed', 'Removed by a teacher'), ('archived', 'Group archived')], max_length=16, verbose_name='leave reason')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='instruction.group', verbose_name='group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='schools.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'group membership',
                'verbose_name_plural': 'group memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_snapshot', models.JSONField(default=list, help_text='Who was in the group when this was written, so it stays coherent.', verbose_name='member snapshot')),
                ('content', models.JSONField(default=dict, verbose_name='content')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('fallback', 'Fallback')], default='generating', max_length=16, verbose_name='status')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('was_helpful', models.BooleanField(blank=True, null=True, verbose_name='was helpful')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('canonical_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptations', to='instruction.canonicallessonplan', verbose_name='canonical source')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='instruction.group', verbose_name='group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='schools.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'lesson plan',
                'verbose_name_plural': 'lesson plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='canonicallessonplan',
            index=models.Index(fields=['focus_subskill', 'from_level', 'resource_tier'], name='canonical_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicallessonplan',
            constraint=models.UniqueConstraint(fields=('domain', 'from_level', 'to_level', 'focus_subskill', 'resource_tier'), name='canonical_plan_signature_unique'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'status'], name='group_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['school', 'domain'], name='group_school_domain_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('level__isnull', True), models.Q(('level__gte', 1), ('level__lte', 5)), _connector='OR'), name='group_criterion_level_in_range'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'left_at'], name='membership_group_open_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['student', 'left_at'], name='membership_student_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('group', 'student'), name='group_membership_one_open_per_student'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['group', '-created_at'], name='plan_group_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['student', '-created_at'], name='plan_student_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('student__isnull', True)), models.Q(('group__isnull', True), ('student__isnull', False)), _connector='OR'), name='lesson_plan_targets_one_thing'),
        ),
    ]
