# Generated by Django 5.2.17 on 2026-08-26 08:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('media_assets', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Optional overall rating; individual questions carry their own level.', max_length=16, verbose_name='difficulty')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('timer', models.DurationField(blank=True, help_text='Time allowed per attempt. Null means untimed.', null=True, verbose_name='timer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=16, verbose_name='status')),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='assessments', to='schools.student', verbose_name='assigned students')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.school', verbose_name='school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='schools.schoolclass', verbose_name='class')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='schools.academicsession', verbose_name='session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='curriculum.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Cleared rather than cascaded so a paper outlives its author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='schools.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='text')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='level')),
                ('order', models.PositiveSmallIntegerField(help_text='Position on the paper; assigned automatically when omitted.', verbose_name='order')),
                ('point', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='point')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('text', 'Text'), ('audio', 'Audio'), ('number', 'Number'), ('true_false', 'True / false'), ('file_upload', 'File upload')], max_length=32, verbose_name='question type')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='assessment')),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='curriculum.questionlayout', verbose_name='layout')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='curriculum.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'assessment question',
                'verbose_name_plural': 'assessment questions',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_average', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='class average')),
                ('participation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of assigned students who submitted.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='participation rate')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='assessments.assessment', verbose_name='assessment')),
                ('most_correct_questions', models.ManyToManyField(blank=True, related_name='analytics_most_correct', to='assessments.assessmentquestion', verbose_name='most correct questions')),
                ('most_missed_questions', models.ManyToManyField(blank=True, related_name='analytics_most_missed', to='assessments.assessmentquestion', verbose_name='most missed questions')),
            ],
            options={
                'verbose_name': 'assessment analytics',
                'verbose_name_plural': 'assessment analytics',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('assessment_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question_answers', to='media_assets.mediaasset', verbose_name='media')),
            ],
            options={
                'verbose_name': 'assessment question answer',
                'verbose_name_plural': 'assessment question answers',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=16, verbose_name='type')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='display order')),
                ('text_content', models.TextField(blank=True, verbose_name='text content')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question_contents', to='media_assets.mediaasset', verbose_name='media')),
            ],
            options={
                'verbose_name': 'assessment question content',
                'verbose_name_plural': 'assessment question contents',
                'ordering': ['assessment_question', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('true_false', 'True / false')], max_length=16, verbose_name='type')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question_options', to='media_assets.mediaasset', verbose_name='media')),
            ],
            options={
                'verbose_name': 'assessment question option',
                'verbose_name_plural': 'assessment question options',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('text', 'Text'), ('audio', 'Audio'), ('number', 'Number'), ('true_false', 'True / false'), ('file_upload', 'File upload')], max_length=32, verbose_name='type')),
                ('text_value', models.TextField(blank=True, verbose_name='text value')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment', verbose_name='assessment')),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='media_assets.mediaasset', verbose_name='media value')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='schools.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'assessment question response',
                'verbose_name_plural': 'assessment question responses',
                'ordering': ['assessment_question__order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionResponseOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='assessments.assessmentquestionoption', verbose_name='option')),
                ('assessment_question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='assessments.assessmentquestionresponse', verbose_name='response')),
            ],
            options={
                'verbose_name': 'assessment question response option',
                'verbose_name_plural': 'assessment question response options',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Null until graded.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='score')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('graded', 'Graded')], default='not_started', max_length=16, verbose_name='status')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment', verbose_name='assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='schools.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'assessment result',
                'verbose_name_plural': 'assessment results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school', 'status', '-due_date'], name='assess_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['teacher', 'status'], name='assess_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school_class', '-due_date'], name='assess_class_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='assessment_question_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 5)), name='assessment_question_level_in_range'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='assessment_answer_requires_value_or_media'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestioncontent',
            constraint=models.UniqueConstraint(fields=('assessment_question', 'display_order'), name='assessment_question_content_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestioncontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text_content', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='assessment_content_requires_text_or_media'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestionoption',
            index=models.Index(fields=['assessment_question', 'is_correct'], name='aq_option_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionoption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='assessment_option_requires_value_or_media'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestionresponse',
            index=models.Index(fields=['assessment', 'student'], name='response_assess_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionresponse',
            constraint=models.UniqueConstraint(fields=('assessment_question', 'student'), name='response_question_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionresponseoption',
            constraint=models.UniqueConstraint(fields=('assessment_question_response', 'assessment_question_option'), name='response_option_unique'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['assessment', 'status'], name='result_assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['student', '-created_at'], name='result_student_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='result_student_assessment_unique'),
        ),
    ]
