# Generated by Django 5.2.17 on 2026-09-04 07:37

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('media_assets', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('code', models.CharField(blank=True, help_text='Typed by the child to open a sitting. Minted at publish.', max_length=16, verbose_name='code')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=16, verbose_name='status')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='opens at')),
                ('closes_at', models.DateTimeField(blank=True, help_text='After this, sittings stop and grouping may run.', null=True, verbose_name='closes at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='schools.school', verbose_name='school')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='schools.academicsession', verbose_name='session')),
                ('teacher', models.ForeignKey(blank=True, help_text='Cleared rather than cascaded so a paper outlives its author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='schools.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="The child's personal code for this paper. Unique within it.", max_length=16, verbose_name='code')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('graded', 'Graded')], default='not_started', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('session_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='session hash')),
                ('session_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='session expires at')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.assessment', verbose_name='assessment')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to='schools.teacher', verbose_name='assigned by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'assessment assignment',
                'verbose_name_plural': 'assessment assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='text')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('fln_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='FLN level')),
                ('order', models.PositiveSmallIntegerField(help_text='Position on the paper; assigned automatically when omitted.', verbose_name='order')),
                ('point', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='point')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('text', 'Text'), ('audio', 'Audio'), ('number', 'Number'), ('true_false', 'True / false'), ('file_upload', 'File upload')], max_length=32, verbose_name='question type')),
                ('layout', models.CharField(blank=True, choices=[('media_grid_choice', 'Media grid'), ('media_list_choice', 'Media list'), ('comparison_panel_choice', 'Comparison panel'), ('speech_response_prompt', 'Speech response'), ('passage_comprehension_choice', 'Passage comprehension')], max_length=32, verbose_name='layout')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='assessment')),
                ('skill', models.ForeignKey(help_text='Denormalised from the subskill so the matrix is a single-table read.', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='curriculum.skill', verbose_name='skill')),
                ('source_question', models.ForeignKey(blank=True, help_text='Set when pulled from the bank; null when the teacher authored it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_copies', to='curriculum.question', verbose_name='source question')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='curriculum.subskill', verbose_name='subskill')),
            ],
            options={
                'verbose_name': 'assessment question',
                'verbose_name_plural': 'assessment questions',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_average', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='class average')),
                ('participation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of assigned students who submitted.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='participation rate')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='assessments.assessment', verbose_name='assessment')),
                ('most_correct_questions', models.ManyToManyField(blank=True, related_name='analytics_most_correct', to='assessments.assessmentquestion', verbose_name='most correct questions')),
                ('most_missed_questions', models.ManyToManyField(blank=True, related_name='analytics_most_missed', to='assessments.assessmentquestion', verbose_name='most missed questions')),
            ],
            options={
                'verbose_name': 'assessment analytics',
                'verbose_name_plural': 'assessment analytics',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('assessment_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question_answers', to='media_assets.mediaasset', verbose_name='media')),
            ],
            options={
                'verbose_name': 'assessment question answer',
                'verbose_name_plural': 'assessment question answers',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=16, verbose_name='type')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='display order')),
                ('text_content', models.TextField(blank=True, verbose_name='text content')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question_contents', to='media_assets.mediaasset', verbose_name='media')),
            ],
            options={
                'verbose_name': 'assessment question content',
                'verbose_name_plural': 'assessment question contents',
                'ordering': ['assessment_question', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('true_false', 'True / false')], max_length=16, verbose_name='type')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question_options', to='media_assets.mediaasset', verbose_name='media')),
            ],
            options={
                'verbose_name': 'assessment question option',
                'verbose_name_plural': 'assessment question options',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('text', 'Text'), ('audio', 'Audio'), ('number', 'Number'), ('true_false', 'True / false'), ('file_upload', 'File upload')], max_length=32, verbose_name='type')),
                ('text_value', models.TextField(blank=True, verbose_name='text value')),
                ('transcript', models.TextField(blank=True, help_text='Speech-to-text output, kept beside the audio so a teacher can verify.', verbose_name='transcript')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='is correct')),
                ('awarded_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='awarded points')),
                ('graded_by', models.CharField(blank=True, choices=[('auto', 'Automatic'), ('ai', 'AI'), ('teacher', 'Teacher')], max_length=16, verbose_name='graded by')),
                ('grading_confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Low confidence routes the response to a teacher for review.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='grading confidence')),
                ('error_type', models.CharField(blank=True, choices=[('no_response', 'No response'), ('substitution', 'Substitution'), ('omission', 'Omission'), ('insertion', 'Insertion'), ('reversal', 'Reversal'), ('self_corrected', 'Self-corrected'), ('place_value', 'Place-value error'), ('operation_confusion', 'Wrong operation'), ('computation', 'Computation slip'), ('partial', 'Partially correct'), ('other', 'Other')], max_length=32, verbose_name='error type')),
                ('observation_note', models.TextField(blank=True, help_text='How the answer was wrong - the detail remediation is built from.', verbose_name='observation note')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment', verbose_name='assessment')),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentquestion', verbose_name='assessment question')),
                ('media_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='media_assets.mediaasset', verbose_name='media value')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='schools.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'assessment question response',
                'verbose_name_plural': 'assessment question responses',
                'ordering': ['assessment_question__order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionResponseOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='assessments.assessmentquestionoption', verbose_name='option')),
                ('assessment_question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='assessments.assessmentquestionresponse', verbose_name='response')),
            ],
            options={
                'verbose_name': 'assessment question response option',
                'verbose_name_plural': 'assessment question response options',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Null until graded.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='score')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('graded', 'Graded')], default='not_started', max_length=16, verbose_name='status')),
                ('items_attempted', models.PositiveSmallIntegerField(default=0, verbose_name='items attempted')),
                ('items_correct', models.PositiveSmallIntegerField(default=0, verbose_name='items correct')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percentage')),
                ('marked_at', models.DateTimeField(blank=True, null=True, verbose_name='marked at')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment', verbose_name='assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='schools.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'assessment result',
                'verbose_name_plural': 'assessment results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('literacy', 'Literacy'), ('numeracy', 'Numeracy')], max_length=16, verbose_name='domain')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('order', models.PositiveSmallIntegerField(verbose_name='order')),
                ('timer', models.DurationField(blank=True, help_text='Time allowed for this sitting. Null means untimed.', null=True, verbose_name='timer')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.assessment', verbose_name='assessment')),
                ('covers', models.ManyToManyField(blank=True, related_name='assessment_sections', to='curriculum.subskill', verbose_name='covers')),
            ],
            options={
                'verbose_name': 'assessment section',
                'verbose_name_plural': 'assessment sections',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmentsection', verbose_name='section'),
        ),
        migrations.CreateModel(
            name='AssessmentSectionResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('in_progress', 'In progress'), ('submitted', 'Submitted')], default='locked', max_length=16, verbose_name='status')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='score')),
                ('items_attempted', models.PositiveSmallIntegerField(default=0, verbose_name='items attempted')),
                ('items_correct', models.PositiveSmallIntegerField(default=0, verbose_name='items correct')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When a timed sitting must end. Set from the section timer on start.', null=True, verbose_name='expires at')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_results', to='assessments.assessmentresult', verbose_name='result')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessmentsection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'assessment section result',
                'verbose_name_plural': 'assessment section results',
                'ordering': ['result', 'section__order'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school', 'status', '-created_at'], name='assess_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['teacher', 'status'], name='assess_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['code'], name='assess_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), condition=models.Q(('code', ''), _negated=True), name='assessment_code_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['assessment', 'status'], name='assignment_assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['student', '-created_at'], name='assignment_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentassignment',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='assignment_assessment_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentassignment',
            constraint=models.UniqueConstraint(models.F('assessment'), django.db.models.functions.text.Upper('code'), name='assignment_assessment_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='assessment_answer_requires_value_or_media'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestioncontent',
            constraint=models.UniqueConstraint(fields=('assessment_question', 'display_order'), name='assessment_question_content_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestioncontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text_content', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='assessment_content_requires_text_or_media'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestionoption',
            index=models.Index(fields=['assessment_question', 'is_correct'], name='aq_option_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionoption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value', ''), _negated=True), ('media__isnull', False), _connector='OR'), name='assessment_option_requires_value_or_media'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestionresponse',
            index=models.Index(fields=['assessment', 'student'], name='response_assess_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionresponse',
            constraint=models.UniqueConstraint(fields=('assessment_question', 'student'), name='response_question_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionresponseoption',
            constraint=models.UniqueConstraint(fields=('assessment_question_response', 'assessment_question_option'), name='response_option_unique'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['assessment', 'status'], name='result_assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['student', '-created_at'], name='result_student_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='result_student_assessment_unique'),
        ),
        migrations.AddIndex(
            model_name='assessmentsection',
            index=models.Index(fields=['assessment', 'order'], name='section_assess_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='assessment_section_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='assessment_question_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.CheckConstraint(condition=models.Q(('fln_level__gte', 1), ('fln_level__lte', 5)), name='assessment_question_level_in_range'),
        ),
        migrations.AddIndex(
            model_name='assessmentsectionresult',
            index=models.Index(fields=['result', 'status'], name='section_result_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsectionresult',
            constraint=models.UniqueConstraint(fields=('result', 'section'), name='section_result_unique'),
        ),
    ]
