# Generated by Django 5.2.17 on 2026-09-04 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('register', 'Verify a new account'), ('login', 'Second factor at sign-in'), ('password_reset', 'Reset a forgotten password'), ('password_reset_confirm', 'Set a new password'), ('delete_teacher', 'Confirm deleting a teacher'), ('delete_student', 'Confirm deleting a student')], db_index=True, max_length=32, verbose_name='purpose')),
                ('code_hash', models.CharField(blank=True, editable=False, max_length=128, verbose_name='code hash')),
                ('challenge_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='challenge hash')),
                ('subject_id', models.UUIDField(blank=True, null=True, verbose_name='subject')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'verification code',
                'verbose_name_plural': 'verification codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose'], name='verification_user_purpose_idx')],
            },
        ),
    ]
