# Generated by Django 5.2.17 on 2026-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Product admin'), ('school', 'School management'), ('teacher', 'Teacher')], db_index=True, default='admin', help_text='Which product surface this identity may sign in to.', max_length=16, verbose_name='role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
    ]
