# Generated by Django 5.2.17 on 2026-09-04 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('mark_text_response', 'Mark a written answer'), ('mark_audio_response', 'Mark a spoken answer'), ('suggest_question_tags', 'Suggest subskill and level'), ('assessment_analytics', 'Explain a class result'), ('student_skill_narrative', "Explain one child's result"), ('lesson_plan_canonical', 'Author a canonical plan'), ('lesson_plan_group', 'Adapt a plan to a group'), ('lesson_plan_student', 'Personalise for one child')], max_length=32, verbose_name='job type')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('invalid', 'Invalid output')], max_length=16, verbose_name='status')),
                ('subject_type', models.CharField(blank=True, help_text='What the call was about, e.g. "assessment_question_response".', max_length=64, verbose_name='subject type')),
                ('subject_id', models.CharField(blank=True, max_length=64, verbose_name='subject id')),
                ('provider', models.CharField(max_length=32, verbose_name='provider')),
                ('model_id', models.CharField(max_length=128, verbose_name='model')),
                ('prompt_version', models.CharField(blank=True, help_text='The document set this call was given, so a change is traceable.', max_length=64, verbose_name='prompt version')),
                ('input_hash', models.CharField(blank=True, db_index=True, help_text='Identical inputs hash alike, which is what makes a repeat visible.', max_length=64, verbose_name='input hash')),
                ('raw_output', models.TextField(blank=True, verbose_name='raw output')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='output tokens')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='latency ms')),
            ],
            options={
                'verbose_name': 'AI generation',
                'verbose_name_plural': 'AI generations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', '-created_at'], name='ai_gen_job_created_idx'), models.Index(fields=['status', '-created_at'], name='ai_gen_status_idx'), models.Index(fields=['subject_type', 'subject_id'], name='ai_gen_subject_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIPromptDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('mark_text_response', 'Mark a written answer'), ('mark_audio_response', 'Mark a spoken answer'), ('suggest_question_tags', 'Suggest subskill and level'), ('assessment_analytics', 'Explain a class result'), ('student_skill_narrative', "Explain one child's result"), ('lesson_plan_canonical', 'Author a canonical plan'), ('lesson_plan_group', 'Adapt a plan to a group'), ('lesson_plan_student', 'Personalise for one child')], max_length=32, verbose_name='job type')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('version', models.CharField(help_text='Bumped when the content changes. Pinned onto each generation.', max_length=32, verbose_name='version')),
                ('content', models.TextField(verbose_name='content')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'AI prompt document',
                'verbose_name_plural': 'AI prompt documents',
                'ordering': ['job_type', 'display_order', 'name'],
                'indexes': [models.Index(fields=['job_type', 'is_active'], name='ai_doc_job_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('job_type', 'name', 'version'), name='ai_prompt_document_unique')],
            },
        ),
    ]
