# Generated by Django 5.2.17 on 2026-09-04 08:01

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='start year')),
                ('end_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1901)], verbose_name='end year')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ['-start_year'],
                'constraints': [models.UniqueConstraint(fields=('start_year', 'end_year'), name='session_year_pair_unique'), models.CheckConstraint(condition=models.Q(('end_year__gt', models.F('start_year'))), name='session_end_year_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='grade_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('abbreviation', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Use 2-12 uppercase letters or digits, e.g. GHS or ROYAL01.', regex='^[A-Z0-9]{2,12}$')], verbose_name='abbreviation')),
                ('class_system', models.CharField(choices=[('grade', 'Grade'), ('primary', 'Primary')], default='grade', max_length=16, verbose_name='class system')),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.academicsession', verbose_name='current session')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_logos', to='media_assets.mediaasset', verbose_name='logo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL, verbose_name='login account')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The arm or stream, e.g. "A" or "2".', max_length=16, verbose_name='name')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='schools.grade', verbose_name='grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['grade__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16, verbose_name='gender')),
                ('is_active', models.BooleanField(default=True, help_text='Students hold no login, so disabling one is a flag here.', verbose_name='active')),
                ('student_id', models.CharField(help_text='Human-facing identifier, prefixed with the school abbreviation.', max_length=32, verbose_name='student id')),
                ('guardian_name', models.CharField(max_length=255, verbose_name='guardian name')),
                ('guardian_phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international or local digits, 7-15 characters.', regex='^\\+?[0-9]{7,15}$')], verbose_name='guardian phone number')),
                ('guardian_email', models.EmailField(blank=True, help_text='Where an assessment link is sent. Not every guardian has one.', max_length=254, verbose_name='guardian email')),
                ('guardian_relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('legal_guardian', 'Legal guardian'), ('other', 'Other')], max_length=32, verbose_name='guardian relationship')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school', verbose_name='school')),
                ('school_class', models.ForeignKey(blank=True, help_text='Only a disabled student may be left without a class.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.schoolclass', verbose_name='class')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(help_text='Human-facing identifier, prefixed with the school abbreviation.', max_length=32, verbose_name='teacher id')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school', verbose_name='school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='schools.schoolclass', verbose_name='class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='login account')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('abbreviation'), name='school_abbreviation_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['school', 'grade'], name='class_school_grade_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(models.F('school'), models.F('grade'), django.db.models.functions.text.Upper('name'), name='class_school_grade_name_unique'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'school_class'], name='student_school_class_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'last_name'], name='student_school_name_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='student_school_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('student_id'), name='student_id_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('school_class__isnull', False), ('is_active', False), _connector='OR'), name='student_active_requires_class'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'school_class'], name='teacher_school_class_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('teacher_id'), name='teacher_id_ci_unique'),
        ),
    ]
