# Generated by Django 5.2.17 on 2026-08-26 08:36

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64, verbose_name='value')),
            ],
            options={
                'verbose_name': 'activity tag',
                'verbose_name_plural': 'activity tags',
                'ordering': ['value'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('value'), name='activity_tag_value_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=255, verbose_name='label')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tags', models.ManyToManyField(blank=True, related_name='activities', to='activities.activitytag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['label'],
            },
        ),
    ]
