# Generated by Django 5.2.17 on 2026-09-04 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('assessment_created', 'Assessment created'), ('assessment_published', 'Assessment published'), ('assessment_assigned', 'Assessment assigned'), ('section_started', 'Section started'), ('section_submitted', 'Section submitted'), ('assessment_submitted', 'Assessment submitted'), ('assessment_marked', 'Assessment marked'), ('student_placed', 'Student placed'), ('group_created', 'Group created'), ('group_member_added', 'Group member added'), ('group_member_removed', 'Group member removed'), ('lesson_plan_generated', 'Lesson plan generated'), ('student_created', 'Student created'), ('student_transferred', 'Student transferred'), ('student_disabled', 'Student disabled'), ('teacher_created', 'Teacher created'), ('teacher_disabled', 'Teacher disabled')], max_length=32, verbose_name='action')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='occurred at')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='assessments.assessment', verbose_name='assessment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schools.school', verbose_name='school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='schools.schoolclass', verbose_name='class')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='schools.student', verbose_name='student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='schools.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['school', '-occurred_at'], name='activity_school_time_idx'), models.Index(fields=['school', 'teacher'], name='activity_school_teacher_idx'), models.Index(fields=['school', 'student'], name='activity_school_student_idx'), models.Index(fields=['school', 'school_class'], name='activity_school_class_idx'), models.Index(fields=['school', 'action'], name='activity_school_action_idx')],
            },
        ),
    ]
